apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: skaffold-service
profiles:
  - name: develop
    build:
      artifacts:
        - image: node-skaffold-service
          docker:
            dockerfile: Dockerfile
      local:
        useDockerCLI: true
    deploy:
      kustomize:
        paths:
        - k8s/develop
  - name: prod
    build:
      artifacts:
        - image: gcr.io/cuemby-io/ccp/node-skaffold-service
          docker:
            dockerfile: Dockerfile
      local:
        useDockerCLI: false
        useBuildkit: false
    deploy:
      kustomize:
        paths:
        - k8s/prod