apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skaffold-service

bases:
  - ../base

namePrefix: cuemby-

commonLabels:
  lang: node
  app: skaffold-service

images:
  - name: node-skaffold-service
    newName: node-skaffold-service

configMapGenerator:
  - name: configmap-envs
    behavior: merge
    literals:
      - PORT=8080

secretGenerator:
  - name: secrets-envs
    behavior: merge
    type: Opaque
    files:
    - PG_PASSWORD=private/pg_password.env