apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-skaffold

bases:
  - ../base

namePrefix: test-

commonLabels:
  lang: node
  app: testskaffold-service

images:
  - name: node-test-skaffold-service
    newName: gcr.io/cuemby-io/ccp/node-test-skaffold-service
    
configMapGenerator:
  - name: configmap-envs
    behavior: merge
    literals:
      - PORT=8080