apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-service-deployment
spec:
  selector:
   matchLabels:
    app: skaffold-service
  replicas: 1
  template:
    metadata:
      labels:
        app: skaffold-service
    spec:
      containers:
        - name: skaffold-service
          image: node-skaffold-service
          imagePullPolicy: IfNotPresent     
          ports:
            - containerPort: 8080
              name: skaffoldport
          resources:
            limits:
              memory: 512Mi
              cpu: "0.1"
            requests:
              memory: 256Mi
              cpu: "0.05"
          envFrom:
            - configMapRef:
                name: configmap-envs
            - secretRef:
                name: secrets-envs