apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  
commonLabels:
  type: service
  interface: http
  project: cuemby
  component: skaffold

configMapGenerator:
  - name: configmap-envs

secretGenerator:
  - name: secrets-envs